### ISSUE TITLE
Can't import Cmrr nor instantiate it

### ISSUE THREAD

**Issue by nicotrozzo** [e-neuman/telekinesis#2]
I'm not sure I'm doing things well, but I had the following problems:
1. When trying to import Cmrr from the installed camarere module, it doesn't seem to have a 'Cmrr' class to import. I went to the files pip installed at C:\Users\myName\AppData\Local\Miniconda3\Lib\site-packages\camarere and I have 'client.py', 'common.py' and 'hub.py', but the client.py differs from the 'client.py' file you have in master where I can see the Cmrr class.
2. I tried cloning the repo and importing the file doing `from client.camarere import Cmrr`. It obviously finds the class but when running `cmrr = Cmrr('https://cmrr.es')` I get the following:

> Traceback (most recent call last):
  File "C:/Users/nicot/OneDrive/Documents/PycharmProjects/camarere/main.py", line 5, in <module>
    cmrr = Cmrr('https://cmrr.es')
  File "C:\Users\nicot\OneDrive\Documents\PycharmProjects\camarere\client\camarere\client.py", line 11, in __init__
    user_data = requests.get(self.url+'tmp_user').json()
  File "C:\Users\nicot\AppData\Local\Miniconda3\lib\site-packages\requests\models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\nicot\AppData\Local\Miniconda3\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\nicot\AppData\Local\Miniconda3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\nicot\AppData\Local\Miniconda3\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

PS: It's the first issue I submit on GitHub so I'm sorry if it doesn't follow some of the usual standards.

**Comment by e-neuman** [comment]
Hi Nico, thank you for submitting the issue, and sorry for the delayed response, I was working on a big pull request (as you shall see).

I had made a change to the API but hadn't updated the README.

This should be fixed now (you will notice a big change in names, camarere is now called telekinesis)

I hope you like the changes and improved functionality, and let me know if you encounter any issues, I promise to respond quicker!

**Comment by nicotrozzo** [comment]
Great! Now it looks better. I don't really need it right now but I saw it on my feed and liked the idea. I'll give it a try.

**Comment by e-neuman** [comment]
Thank you!!
